### ISSUE TITLE
Is there any way to import a Supertable with inner Matrix fields?

### ISSUE THREAD

**Issue by pixeljitsu** [engram-design/FieldManager#10]
I have a complex matrix field set I want to be able to include in a super table.  Is there any way do to this?

**Comment by pixeljitsu** [comment]
Nevermind, I had a version conflict in the exported fields.

**Comment by engram-design** [comment]
@pixeljitsu Yeah, this was added in one of the latest versions, but there were some bugs in 1.3.3. Glad you got it working!
