### ISSUE TITLE
Import into exiting matrix field

### ISSUE THREAD

**Issue by wmdhosting** [engram-design/FieldManager#103]
### Describe the bug

Dont know if i get it right.. this is just simple example

I want to import >> Update exiting matrix field  with same handle names and fields, just add new one

![2024-07-09_15-11-35](https://github.com/verbb/field-manager/assets/76176291/464d3a3b-a037-4f3f-9924-3205cc878fac)

### Steps to reproduce

Explained on image , what i want to do. but get this kind of error 

![2024-07-09_15-15-33](https://github.com/verbb/field-manager/assets/76176291/441875c5-c6ea-497e-bab0-8ef0fe26a714)

### Craft CMS version

5.2.2.

### Plugin version

4.0.1

### Multi-site?

N

**Comment by engram-design** [comment]
Looks like there's an issue in both the export and import of Matrix fields. You'll need to re-export your Matrix fields.

Fixed for the next release. To get this early, run `composer require verbb/field-manager:"dev-craft-5 as 4.0.1"`.

**Comment by engram-design** [comment]
Fixed in [4.0.2](https://github.com/verbb/field-manager/releases/tag/4.0.2)
