### ISSUE TITLE
Fix for Matrix -> ST -> Matrix cloning and import/export

### ISSUE THREAD

**Issue by engram-design** [engram-design/FieldManager#11]

**Comment by davidhellmann** [comment]
Same problem here. It's not possible to Clone Fields they have matrix > supertable in it.

**Comment by engram-design** [comment]
At this time, its not supported, but will be in the future. I'll keep you posted.

However, a Super Table > Matrix or Matrix > Super Table will work with cloning or import/export.

**Comment by engram-design** [comment]
This is now fixed in version [1.5.0](https://github.com/engram-design/FieldManager/releases/tag/1.5.0).
