### ISSUE TITLE
Cloning Super Table field causes original to loose it's settings

### ISSUE THREAD

**Issue by bonzidrine** [engram-design/FieldManager#13]
When cloning a Super Table field the first time, the cloned field is a good copy.
But the original, cloned field has lost it's settings / columns. 

When I edit the page with both fields (original & cloned) the original field no longer has it's column names.

When saved and editing again, the original field is nothing more but a horizontal line where the field should be.

Also, when I try to clone the original a second time (before I edit the page with original & cloned field), all the Super Table settings are also gone.

This happens on Craft Pro 2.4.2700

**Comment by engram-design** [comment]
Thanks for reporting this - its now fixed in the [1.4.1 release](https://github.com/engram-design/FieldManager/releases/tag/1.4.1).
