### ISSUE TITLE
Cloning a matrix doesn't copy over block instructions

### ISSUE THREAD

**Issue by davidrleonard** [engram-design/FieldManager#17]
When I clone a matrix, the instructions for sub-blocks aren't saved for the new cloned matrix.

When I clone, I get the modal that lets me edit the instructions for each block. The text appears to carry over. But when I hit save, all instruction text is wiped out on the new cloned matrix.

I'm on Craft 2.5.2762.

(Also, thanks for your work on this project!)

**Comment by davidrleonard** [comment]
Just to update ... it looks like there's more weirdness in matrix cloning. Any edits made to my cloned matrix in the edit modal on the FieldManager page don't save. In addition, some things just don't copy over (i.e. the instructions for each matrix block).

**Comment by engram-design** [comment]
Thanks @davidrleonard I've pushed a fix for the instructions issue with Matrix fields. I've checked all other settings, etc copy over fine, so it was just an issue with the instructions field. Check out [version 1.4.3](https://github.com/engram-design/FieldManager/releases/tag/1.4.3).

I also can't replicate any issues when editing the cloned Matrix field. I've tested editing the core Matrix fields, along with any fields inside a block type. Can you confirm this is still happening, and perhaps post the steps you're doing to reproduce?

**Comment by engram-design** [comment]
Following up on this, Matrix import/export cloning has been totally rewritten, and tested pretty thoroughly. Check out version [1.5.0](https://github.com/engram-design/FieldManager/releases/tag/1.5.0), and reopen if you still encounter issues.
