### ISSUE TITLE
Export file is missing closing brackets

### ISSUE THREAD

**Issue by matt-tile** [engram-design/FieldManager#18]
I had to add three closing brackets to make the import of export.json succeed. Export file is 1800 lines long and is composed of 20 blocks.

**Comment by engram-design** [comment]
I'd be interested to see if this was a memory-related issue or not? I've done countless exports and none seem to have cut off as you describe - most over 2,500 lines long.

**Comment by engram-design** [comment]
Closing for now. Please reopen if this is still an issue.
