### ISSUE TITLE
JSON_PRETTY_PRINT PHP Error

### ISSUE THREAD

**Issue by Natetronn** [engram-design/FieldManager#2]
Not sure it's me or not but, did want to add this just in case it's not me. Let me know if there is any more information you need from me

![JSON_PRETTY_PRINT](https://monosnap.com/file/MfnDmqfmPHVgCbnMew4SXZq6ZWad5w.png)

**Comment by Natetronn** [comment]
Okay, it's me: http://stackoverflow.com/a/19305475/585191

**Comment by engram-design** [comment]
Nice catch - I'd rather provide 5.3 support, so will fix this!

**Comment by Natetronn** [comment]
That's good since Craft currently supports 5.3.0. I've heard "rumors" in the Slack chat that v.3 will be move up to 5.4 or above fwiw.

**Comment by engram-design** [comment]
Yeah cool - my general rule is to test against 5.3, so thats on me :) Fixed in latest commit.
