### ISSUE TITLE
Receiving Internal Server Error on /admin/fieldmanager

### ISSUE THREAD

**Issue by RobErskine** [engram-design/FieldManager#20]
```
## Internal Server Error
CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'craft_fields.id' in 'field list'
```

Am I missing something silly? This is working on my other Craft installs, but not my latest build running Craft 2.6.2774

**Comment by engram-design** [comment]
Hmm - can't seem to replicate that on a few different environments. Are there are other plugin that might be messing with things? Does the error happen when you simply navigate to the Field Manager page (you're not trying to do anything)?

**Comment by tcsehv** [comment]
@RobErskine do you use a custom table prefix?

I created a pull request for the issue. See #21

**Comment by engram-design** [comment]
Ah - yeah thats totally a valid point. @tcsehv Thanks for submitting that PR - adding it to the next release.

**Comment by RobErskine** [comment]
@tcsehv yeah that was exactly it. @engram-design thanks for jumping on it so soon!
