### ISSUE TITLE
Cloning matrix causes error in Entry

### ISSUE THREAD

**Issue by dGilli** [engram-design/FieldManager#28]
After Cloned matrix has been added to a section this Error pops up when trying to edit entry:

```
Internal server error

CDbCommand could not execute the SQL statement : SQLSTATE [ 42S22 ] : Column not found : 1054 Unknown column ' content.field_headingBlock_heading ' in ' field list'
```
The new matrix field needs to be saved manually again for it to work correctly again.

**Comment by engram-design** [comment]
This is now fixed in version [1.5.0](https://github.com/engram-design/FieldManager/releases/tag/1.5.0).
