### ISSUE TITLE
Cloning Matrix field deletes matrix blocks from original field

### ISSUE THREAD

**Issue by OvidiuS** [engram-design/FieldManager#32]
Craft version: 2.6.2796
Environment: Scotch Box 2.5 on VirtuaBox 5.0

Steps:
1. Create matrix-field-1 with blocks and fields inside the blocks (nothing but default Craft fields, nothing else installed)
2. Install the FieldManager plugin.
3. Clone matrix-field-1 into matrix-field-2
4. matrix-field-2 has all the blocks and fields from matrix-field-1
5. BUG: matrix-field-1 has no blocks anymore.

Please let me know if you need more info.

**Comment by engram-design** [comment]
Are you on the latest version of field manager?

**Comment by OvidiuS** [comment]
yes, just downloaded it from this github repo.

**Comment by joelkesler** [comment]
Noticed the same thing

**Comment by engram-design** [comment]
Thanks guys, will push a fix for this very soon.

**Comment by janhendrickx** [comment]
Same problem here, newest Craft version & newest Field Manager version. Tested it twice, and it had the same problem both times.

**Comment by engram-design** [comment]
Thanks @janhendrickx - aware of this issue.

**Comment by engram-design** [comment]
Sorry for the delay everyone, fixed in the latest master, and will be rolled into the next release.

**Comment by davecoggins** [comment]
I've download the latest version but the clone field is now throwing an internal 500 server error when trying to clone a matrix field

`jquery-2.2.1.min.js?d=1468347771:4 POST http://test.craft.dev/index.php?p=admin/actions/fieldManager/cloneField 500 (Internal Server Error)`

**Comment by engram-design** [comment]
Yep, just realised a typo - thats what happens with late night/early morning commits...

**Comment by engram-design** [comment]
@davecoggins Ended up refactoring a little for better results. Should be good to go now.

**Comment by engram-design** [comment]
Fixed in [1.5.2](https://github.com/engram-design/FieldManager/releases/tag/1.5.2)

**Comment by engram-design** [comment]
@davecoggins I can't seem to replicate this I'm afraid.

Its very possible this was left over from previous versions as above where this was an issue. To rectify, you should just save your cloned Matrix field again, then try to save your entry. Or did you clone this field directly in 1.5.2?

**Comment by kotyy** [comment]
Can I suggest you put a message at the top of your README about this? Using Craft 2.6.2903 and just discovered this. Unfortunately, I didn't check for the presence of the previous blocks before deleting them from the cloned copy. Guess I shouldn't have put off the plugin updates. :)

I love the plugin, I just don't want anyone else to encounter this.
