### ISSUE TITLE
Field Manager does not bring in position select options in matrix block

### ISSUE THREAD

**Issue by joelkesler** [engram-design/FieldManager#33]
Field Manager does not bring in position select options in matrix block.

To test this, I imported the "articleBody" matrix field from the Happy Lager Craft Demo site.  Everything came across except the Position Select options. 

The options for the Position Select field were saved in the json file, however.

[export.json.txt](https://github.com/engram-design/FieldManager/files/372520/export.json.txt)

**Comment by engram-design** [comment]
I can recall the position select field acts a little differently than pretty much any other field! Will push a fix for this very soon.

**Comment by engram-design** [comment]
Should work now as of the latest master! Rolling into the next release.

**Comment by engram-design** [comment]
Fixed in [1.5.2](https://github.com/engram-design/FieldManager/releases/tag/1.5.2)
