### ISSUE TITLE
Call to a member function prepSettings() on null

### ISSUE THREAD

**Issue by mcclaskiem** [engram-design/FieldManager#34]
This happened after configuring the import using the latest release. The error is being thrown by Craft's FieldsService not the plug-in it self. Any idea how to remedy this?
![screen shot 2016-07-20 at 10 19 32 am](https://cloud.githubusercontent.com/assets/6970287/16989782/80b92ea8-4e63-11e6-982f-75ede5a10d5c.png)

**Comment by engram-design** [comment]
Any chance you could send through the json you're using for the import? Feel free to DM me in the Slack channel (@crawf) if you'd rather it not public.

**Comment by engram-design** [comment]
Fixed in [1.5.2](https://github.com/engram-design/FieldManager/releases/tag/1.5.2)
