### ISSUE TITLE
Error Message json_decode() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by brianbier** [engram-design/FieldManager#36]
When I try importing the smart map field from the smart map plugin. It throw the above error.

**Comment by brianbier** [comment]
here is the plugin I am referring too [Link](https://craftpl.us/plugins/smart-map/)

**Comment by lenchantin** [comment]
My agency uses smart map quite a bit as well. Any updates on this?

@brianbier -- I know this isn't the best long term solution, but until there's a fix, we simply add a plain text field called "address" or whatever we name it in the master template file, then when the plugin is installed on the new server we're migrating to, we switch the plain text to the Smart Maps plugin. :) Just have to remember to change it.

**Comment by engram-design** [comment]
Smart Map support has been added in [1.5.3](https://github.com/engram-design/FieldManager/releases/tag/1.5.3) as it needed a bit of a special case
