### ISSUE TITLE
Field Handle being overwritten on form submit 

### ISSUE THREAD

**Issue by kboduch** [engram-design/FieldManager#38]
Lets use this import JSON as an example:

 	[{
		"name": "Body",
		"handle": "newsroomCampaignBody",
		"instructions": "",
		"required": false,
		"translatable": 0,
		"type": "CKEditor_CKEditor",
		"settings": null
	}]

![field_manager_-_national_honey_board](https://cloud.githubusercontent.com/assets/3485537/22822275/00475c14-ef7f-11e6-9801-64a41762f990.png)

When I hit Import button `Field Handle` changes to "body"

And as expected

![field_manager_-_national_honey_board](https://cloud.githubusercontent.com/assets/3485537/22822355/6d34f7d2-ef7f-11e6-8da0-1d1703f97643.png)

**Comment by engram-design** [comment]
Fixed in the [latest master](https://github.com/engram-design/FieldManager/archive/master.zip), thanks for reporting!
