### ISSUE TITLE
FIeld handles being overridden on import

### ISSUE THREAD

**Issue by bhuvidya** [engram-design/FieldManager#39]
Love this plugin. But the one issue i have found is that the field handles that I load from an import json file are initially loaded into the handle field onscreen ok, but when I click "Import" the handle fields are adjusted to be a slugified version of the field name, as though I had just entered the names and no handles.

So obviously this is only an issue if the handle differs from the slugified version of a field title. For example, if a field has a name `Caption`, and a handle of `imgCaption`, when I do the import the handle gets adjusted to `caption`.

I haven't had a chance to look at the code yet, but if I do I'll see if i can put together a PR.

Cheers.

**Comment by engram-design** [comment]
Ah, just released I hadn't rolled this change into a release yet! This should be fixed in the [latest master](https://github.com/engram-design/FieldManager/archive/master.zip)

**Comment by bhuvidya** [comment]
Super! Thanks Josh.

**Comment by bhuvidya** [comment]
Ok, fwiw just confirmed it's all good! Thanks mate.
