### ISSUE TITLE
Feature Request: Show which element types use which fields

### ISSUE THREAD

**Issue by davist11** [engram-design/FieldManager#47]
Basically, I would love to see what <a href="https://github.com/jmuspratt/craft-fieldguide">Field Guide</a> does baked into Field Manager. Instead of having to install both, it would be great if you could see which fields are used in specific element types in Field Manager.

**Comment by engram-design** [comment]
There's also https://github.com/doublesecretagency/craft-inventory for Craft 3 for the moment! It's added to our feature list though.

**Comment by engram-design** [comment]
Added an Audit tab in [2.1.0](https://github.com/verbb/field-manager/releases/tag/2.1.0) to see what elements use what, etc.
