### ISSUE TITLE
Unknown property error when exporting Super Table field

### ISSUE THREAD

**Issue by KatieMFritz** [engram-design/FieldManager#49]
### Description
When I try to export any Super Table field in Craft 3, I get an error:
`Getting unknown property: craft\web\Application::superTable`

Full stack trace screenshot below. 

### Steps to reproduce

1. Install Super Table plugin in Craft 3 
2. Create a Super Table Field
3. In Field Manager menu, select the new Super Table Field
4. Select "Export"

### Additional info

- Field Manager Plugin version: 2.02
- Super Table plugin version: 2.0.5
- Craft version: Craft Pro 3.0.2

![screenshot-safs local-2018 04 11-14-40-39](https://user-images.githubusercontent.com/7085184/38636525-6cff2a88-3d96-11e8-9278-8404abfd73ff.png)

**Comment by KatieMFritz** [comment]
Is this fixed in https://github.com/verbb/field-manager/commit/037a80ca7aa544c280538284b483bfbd3d81dc8f?

**Comment by KatieMFritz** [comment]
SOLVED: Until https://github.com/verbb/field-manager/commit/037a80ca7aa544c280538284b483bfbd3d81dc8f gets released, update `composer.json` to 
`"verbb/field-manager": "dev-craft-3#037a80ca7aa544c280538284b483bfbd3d81dc8f"` and run `composer update`.

**Comment by KatieMFritz** [comment]
Welp, that lets me export SuperTable fields as JSON, but **importing them fails silently** - the process seems to work and says it's successful, but the fields don't show up.

### Steps to reproduce:

1. Paste JSON
![screenshot-167 99 12 106-2018 04 12-08-53-45](https://user-images.githubusercontent.com/7085184/38678503-2ae57dfc-3e2f-11e8-9c32-28d5f04398eb.png)

2. Configure Import
![screenshot-167 99 12 106-2018 04 12-08-54-02](https://user-images.githubusercontent.com/7085184/38678509-2ebf3e2c-3e2f-11e8-827a-742483c6dceb.png)

3. "Imported successfully" 
![imported-successfully](https://user-images.githubusercontent.com/7085184/38678546-4cf44af4-3e2f-11e8-9d09-633c993ac1d1.PNG)

4. Imported field does not appear in field list

**Comment by KatieMFritz** [comment]
So, I hadn't actually _installed_ SuperTable on my remote site, just pushed the files. That did the trick Sorry! 😅

**Comment by engram-design** [comment]
Whoops, thanks for reminding me this commit hasn't been tagged in a release! Glad you got to the bottom of everything though, and sorry for the inconvenience!

Regarding your last comment, is it importing them correctly, or still silently failing? I know its been a while, so you've likely forgotten 😅
