### ISSUE TITLE
Control panel icon path wrong

### ISSUE THREAD

**Issue by loshose** [engram-design/FieldManager#50]
### Description
The icon for Field Manager has a wrong path, which is pointing to the system drive of the server:
`<span class="icon icon-mask"><span data-icon="X:\something\www.name-of-the-site.fi\vendor\verbb\field-manager\src\icon-mask.svg"></span></span>`

### Steps to reproduce

1. I think this wasn't a problem in the earlier versions of the plugin, so steps to reproduce are to install the 2.0.2 version of the plugin.
2. Look at the left side of the control panel.

### Additional info

- Plugin version: Field Manager 2.0.2
- Craft version: Craft CMS 3.0.10.1

**Comment by engram-design** [comment]
I don't believe this is a Field Manager issue, as Craft itself deals with the path to this icon. Also, 2.0.2 is the latest released version, so did you mean 2.0.1 worked where 2.0.2 didn't?

**Comment by engram-design** [comment]
Closing for the moment - just let me know if you're still having issues!
