### ISSUE TITLE
Cannot change the field type

### ISSUE THREAD

**Issue by terryupton** [engram-design/FieldManager#53]
### Description
Once a field has been created, it isn't possible to change the field type in Field Manager. The dropdown only shows that of the original field type selected.
<img width="886" alt="screen shot 2018-09-11 at 15 30 56" src="https://user-images.githubusercontent.com/5698596/45367282-cf488580-b5d8-11e8-9b5f-c0b838323137.png">

### Steps to reproduce

1. Create a field.
2. Edit the field in field manager and change the entry type dropdown.

### Additional info

- Plugin version:  2.0.2
- Craft version: Craft CMS 3.0.23.1

**Comment by terryupton** [comment]
A little further investigation, it seems this is a bug when certain fields types are used.
As an example, if an entries, assets, supertable field is used then this is not editable and only shows the selected field-type object. See the following screenshots:
<img width="1214" alt="screen shot 2018-09-11 at 15 40 26" src="https://user-images.githubusercontent.com/5698596/45367439-28181e00-b5d9-11e8-8dd7-46a5e660019a.png">
<img width="1200" alt="screen shot 2018-09-11 at 15 40 00" src="https://user-images.githubusercontent.com/5698596/45367448-2cdcd200-b5d9-11e8-8727-7726184c272f.png">
<img width="886" alt="screen shot 2018-09-11 at 15 30 56" src="https://user-images.githubusercontent.com/5698596/45367453-31a18600-b5d9-11e8-8c36-41d8a7256898.png">

However, when the field type was set to Plan Text initially, the options to change to _some_ alternative field types was available.
<img width="1223" alt="screen shot 2018-09-11 at 15 40 11" src="https://user-images.githubusercontent.com/5698596/45367505-4b42cd80-b5d9-11e8-8cbc-b9f5d91942d6.png">

**Comment by engram-design** [comment]
This is fixed in the [2.0.3](https://github.com/verbb/field-manager/releases/tag/2.0.3) release.
