### ISSUE TITLE
Cloning Neo Field deletes original neo fields 

### ISSUE THREAD

**Issue by wihodges** [engram-design/FieldManager#55]
### Description
When you clone a Neo field, the original cloned Neo field loses all of its fields and thus loses all of the content yikes!

Looks like there might be similar past issue to matrix. 

### Steps to reproduce

1. Clone Neo field

### Additional info

- Plugin version: 2.0.4
- Craft version: 3.0.33

**Comment by engram-design** [comment]
Neo fields are not currently supported, but we'll at least improve this in the short-term to not mess around with the original field.

**Comment by wihodges** [comment]
I guess in near term I wonder if there is a way to not allow for the user to clone unsupported field types. 

Appreciate the plugin otherwise! Thanks

**Comment by wihodges** [comment]
FYI for anyone who finds this: good news is when you recreate the Neo field with the exact same fields, the data comes back.

**Comment by engram-design** [comment]
Neo field cloning is disabled for the moment, so shouldn't cause further issues
