### ISSUE TITLE
Disallow/hide in environments where 'allowAdminChanges' => false is set

### ISSUE THREAD

**Issue by jsunsawyer** [engram-design/FieldManager#59]
With 3.1 and project config, we want to ensure that no one (even admins who should know better) can't mess up our project config setup.

Checking for `'allowAdminChanges' => false,` (the way that Craft does for Settings) would help prevent accidental changes being made.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/field-manager/releases/tag/2.1.0)
