### ISSUE TITLE
FEATURE-nested matrix field views

### ISSUE THREAD

**Issue by 919Studios** [engram-design/FieldManager#60]
@engram-design  I just grabbed a quick screenshot of what the **import** looks like for this parent matrix.  Everything gets imported perfectly........ If this screen included options for all the nested fields… that would make this plugin **even more awesome** and would be an **incredible productivity feature** for this plugin.

![importScreen-op2-](https://user-images.githubusercontent.com/20955174/56087482-6bba5b00-5e3a-11e9-83fe-2313ef4909fd.png)

_Originally posted by @919Studios in https://github.com/verbb/field-manager/issues/56#issuecomment-482913000_

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/field-manager/releases/tag/2.1.0)
