### ISSUE TITLE
Feature Request: New field is created in currently chosen field group

### ISSUE THREAD

**Issue by vaughn-taylor** [engram-design/FieldManager#64]
It would be great if a new field is created within the currently chosen field group. As it is, the new field is automatically created in the first available field group. For example, assume the following field groups:

-- Global Elements
-- Common Elements

If I click the field group "Common Elements" then click "New Field", the new field would be created within the "Global Elements" field group.

**Comment by engram-design** [comment]
Added in [2.1.1](https://github.com/verbb/field-manager/releases/tag/2.1.1)
