### ISSUE TITLE
zendframework warnings on installation

### ISSUE THREAD

**Issue by olets** [engram-design/FieldManager#65]
### Description

I get these warnings during installation

```
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
```

### Steps to reproduce

1. `composer require verbb/field-manager`

### Additional info

- Plugin version: 2.1.1
- Craft version: 3.3.18.1

**Comment by engram-design** [comment]
This isn't a Field Manager issue, instead a Craft one see https://github.com/craftcms/cms/issues/5439 and https://github.com/craftcms/cms/issues/5400
