### ISSUE TITLE
When cloning a matrix field, some fields' order and settings are lost.

### ISSUE THREAD

**Issue by andreimoment** [engram-design/FieldManager#66]
### Description
When cloning a matrix field, the sub-fields' order is lost, and all sub-fields have the "Use this field’s values as search keywords?" checked.

### Steps to reproduce

1. Create a matrix field with two fields, each with four distinct sub-fields. Un-check the "Use this field’s values as search keywords?" checkbox for each of the sub-fields.
2. Save it and clone it.
3. The newly created matrix field will have the four sub-fields in a different order than the original's. All "Use this field’s values as search keywords?" checkboxes are checked.

### Additional info

- Plugin version: 2.1.1
- Craft version: 3.4.12

**Comment by engram-design** [comment]
Fixed in [2.1.6](https://github.com/verbb/field-manager/releases/tag/2.1.6)
