### ISSUE TITLE
Unable to clone Super Table field that has Matrix field

### ISSUE THREAD

**Issue by kenvunz** [engram-design/FieldManager#68]
### Description
The plugin throws an error `Block Types should contain at least 1 item` when trying to clone a `Super Table` field that has a `Matrix` field

### Steps to reproduce

1. Create a Super Table that has a Matrix field in it
2. Got to `Field Manager` and clone that field

### Additional info

- Plugin version: 2.1.6
- Craft version: 3.4.27
- Super Table version: 2.5.1

**Comment by engram-design** [comment]
Fixed in [2.1.7](https://github.com/verbb/field-manager/releases/tag/2.1.7)
