### ISSUE TITLE
Cannot create a table with a Table Column with dropdown field type

### ISSUE THREAD

**Issue by terryupton** [engram-design/FieldManager#69]
### Description
As per the description, I get an 'a server error occurred' when trying to create a table with a Table Column with a dropdown field type. If I remove the dropdown or change to a single lie then the field saves ok.

This works ok if I do it not using the Field Manager plugin.

### Steps to reproduce

1.create a new field with type as table
2. create a new table column with type as dropdown
3. Save
4. 'a server error occurred'

### Additional info

- Craft version: Craft Pro 3.4.28.1
- PHP version: 7.2.31
- Database driver & version: MySQL 5.5.5 (MariaDB 10.4)

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/field-manager/releases/tag/2.1.8)
