### ISSUE TITLE
Filter for "orphaned" custom fields

### ISSUE THREAD

**Issue by johndwells** [engram-design/FieldManager#7]
It might be handy to show any custom field that isn't currently assigned to a field layout?

:)

**Comment by engram-design** [comment]
@johndwells I'll add this to the roadmap. For anything looking for an immediate solutions, check out [Field Guide](https://github.com/jmuspratt/craft-fieldguide).

**Comment by engram-design** [comment]
Love this idea (finally got to it!) - they're now noted as being 'unused' fields. Check out [version 1.4.3](https://github.com/engram-design/FieldManager/releases/tag/1.4.3).
