### ISSUE TITLE
Existing field handle overwritten upon edit

### ISSUE THREAD

**Issue by lhs-dev** [engram-design/FieldManager#72]
**Description**

When I edit an existing field, its handle is overwritten with the slugified version of its title.

**Steps to reproduce**
1. From the field manager, edit an existing field (field name: **Content builders - Pages de contenu**, handle: `contentBuildersMain`)
2. When the edit modal has finished loading, the correct handle is displayed (`contentBuildersMain`)
3. [Optional] Make some edits 
4. Click the save button
5. While the field is saving, before the modal window is closed, notice the handle has changed (`contentBuildersPagesDeContenu`)

**Additional info**
- Plugin version: 2.1.8
- Craft version: 3.4.x and 3.5.x
- Multi-site: Yes

**Additional context**

This happens every time, except when I make some changes to the handle myself:

1. From the field manager, edit an existing field (field name: **Content builders - Pages de contenu**, handle: `contentBuildersMain`)
2. When the edit modal has finished loading, the correct handle is displayed (`contentBuildersMain`)
3. Change the handle to `contentBuildersMainNew` 
4. Click the save button
5. While the field is saving, before the modal window is closed, notice the handle hasn't changed (still `contentBuildersMainNew`)

**Comment by engram-design** [comment]
Pretty sure this was done on purpose at the time, but it's confusing behaviour. I suppose I was trying to make it easy to manage field handles.

Updated in [2.2.0](https://github.com/verbb/field-manager/releases/tag/2.2.0)
