### ISSUE TITLE
Redactor field in Matrix field can't clone

### ISSUE THREAD

**Issue by mersy** [engram-design/FieldManager#74]
**Description**
Redactor field in a block within Matrix field can't clone  matrix field cloned.

before
![image](https://user-images.githubusercontent.com/205165/93655021-ed64de00-fa5b-11ea-9f88-d25e0c39b878.png)

cloned
![image](https://user-images.githubusercontent.com/205165/93655034-0077ae00-fa5c-11ea-88ec-a323b57a40a4.png)

Export Matrix field and import it , no problem.

**Steps to reproduce**
1. Field Manager > Fields , clone a matrix field

**Additional info**
- Plugin version: 2.2.0
- Craft version: 3.5.11.1
- Multi-site: No

**Comment by brimby** [comment]
I ran into this same bug. I fixed it and submitted a pull request, but if you need to fix yours before the pull request gets merged, my fix can be viewed here: [https://github.com/verbb/field-manager/pull/75/files](https://github.com/verbb/field-manager/pull/75/files)

**Comment by engram-design** [comment]
Thanks @brimby for your PR, added in [2.2.1](https://github.com/verbb/field-manager/releases/tag/2.2.1)
