### ISSUE TITLE
Cannot duplicate NEO field

### ISSUE THREAD

**Issue by luke-nehemedia** [engram-design/FieldManager#76]
When trying to duplicate Neo fields (tried different ones) I get the following error message: 

> yii\base\ErrorException: Undefined index: maxSiblingBlocks in /.../craft3/vendor/spicyweb/craft-neo/src/Field.php:224

At first I thought there was something wrong with my field since it is quite large and complex. I tried another (simpler) one and had the same problem & error message.

**Additional info**
- Plugin version: 2.8.15.1 (latest)
- Craft version: 3.5.17.1 (latest - German locale)
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [2.2.2](https://github.com/verbb/field-manager/releases/tag/2.2.2)
