### ISSUE TITLE
Page Not Found after clicking "Save" on field import

### ISSUE THREAD

**Issue by bryantAXS** [engram-design/FieldManager#77]
**Description**
After clicking Save on the field import screen, I'm getting a Page Not Found error in the CMS.

https://share.getcloudapp.com/NQuJqpkK

**Steps to reproduce**
1. Import tab
2. Paste in Import JSON
3. Add new Field Group
4. Click Save

**Additional info**
- Plugin version: 2.2
- Craft version: 3.5.19.1
- Multi-site: No

**Additional context**

**Comment by bryantAXS** [comment]
Oh, I'm actually seeing that the Save button actually isn't the right button in this case!

It's the Import button that I need to be pressing!

I think this is more of a UX problem actually. The button issue is probably a little confusing, and also that after I click "Import" I'm taken back to the Import tab itself, with my JSON still inside it. I didn't actually realize anything happened.

Either way, I think this issue is resolved, but I'll let you close it after you've read through the comments.

Thanks for the free plugin -- saving me tons of time!

**Comment by engram-design** [comment]
Yep, sorry about that - please use the "Import" button - that Save button just needs to be removed.

And there is a small error/success notice shown, which I suppose can be easily missed. I'll look to improve that.

**Comment by bryantAXS** [comment]
No worries, closing!

**Comment by engram-design** [comment]
Will keep it open so I remember to fix 👍

**Comment by brandondeweese** [comment]
Nothing is imported when I click "Import". Just brings me back to the "configure import".

**Comment by engram-design** [comment]
@brandondeweese It should return to that page, but there's a CP alert that shows success or an error. Are you not seeing that?

**Comment by engram-design** [comment]
Fixed in [2.2.3](https://github.com/verbb/field-manager/releases/tag/2.2.3)
