### ISSUE TITLE
Supertable fields not exported

### ISSUE THREAD

**Issue by johnwbaxter** [engram-design/FieldManager#8]
Hi,

I'm using the latest Field Manager code and the latest Craft build.

When cloning a matrix field with a supertable in it, it doesn't export any of the settings, also, if you hit clone and then start modifying the fields, and then click the "cog" next to a field that has config settings, it opens the config modal, but closes the clone modal so you lose that!

Thanks

John

**Comment by engram-design** [comment]
@johnwbaxter Thanks for letting me know about this. I've fixed the import/export functionality for Matrix and SuperTable fields in the latest release so they should work a treat!

I also can't seem to replicate the modal window issue. I know exactly what you mean, but clicking the cog icon opens up another modal on top of the clone modal. Clicking Close on the ST modal still shows the Clone Modal. Will have to investigate further...

**Comment by johnwbaxter** [comment]
Hey Josh, which latest release? A to be released release?

If i get time later, i'll give you a better report on the scenario that led to the modal issue!

Thanks :)

**Comment by engram-design** [comment]
This latest release! [1.3.4](https://github.com/engram-design/FieldManager/releases/tag/1.3.4) :smile:

**Comment by johnwbaxter** [comment]
Haha! Thanks!! :smile:
