### ISSUE TITLE
Cannot clone Neo fields

### ISSUE THREAD

**Issue by vandres** [engram-design/FieldManager#86]
### Describe the bug

I am trying to clone Neo field. But it always fails with the message "Field layout tab is missing its field layout."

### Steps to reproduce

1.  Create a Neo field with some blocks
2. Try to clone it

### Craft CMS version

4.0.2

### Plugin version

3.0.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/field-manager/releases/tag/3.0.2)

**Comment by vandres** [comment]
Thanks!
