### ISSUE TITLE
"unused" indicator is completely inaccurate

### ISSUE THREAD

**Issue by darylknight** [engram-design/FieldManager#87]
### Describe the bug

The admin/field-manager section is showing 99% of my fields as unused.

Here's the listing:
![image](https://user-images.githubusercontent.com/1250017/186923867-b3302fbc-651e-4386-a1fe-5a6cb3238ecc.png)

And here's a page that is using some of those fields:
![image](https://user-images.githubusercontent.com/1250017/186923932-e21d35b6-1901-414e-ad73-5803d9dfbf1c.png)

### Steps to reproduce

1. Open the field manager

### Craft CMS version

4.2.2

### Plugin version

3.0.2

### Multi-site?

No

### Additional context

I've just installed the plugin, not upgraded from Craft 3

**Comment by engram-design** [comment]
Strange, I can't replicate that on my end whatsoever. The [logic](https://github.com/verbb/field-manager/blob/67ede3becd2ea4a230f5568eebbc2439432d5ef4/src/services/Service.php#L131) for this is pretty simple too  where so long as a field exists in the `fieldlayoutfields` table (as in, it's been added to a field layout _somewhere_) then it's "used".

**Comment by darylknight** [comment]
Anything I can do to help troubleshoot this? It's still happening. Some fields correctly say they're used, but lots of them I know are in use and are reported as Unused

**Comment by engram-design** [comment]
Hmmm, short of sending through your database (which you're most welcome to, if you can to `web at verbb.io`), I'm not sure.

For the ones that say they've been marked as unused, but you know they are - are they in Neo, Vizy/etc fields, or just in sections? Wondering if you can provide an example where we can track it all the way through your install, and cross-reference against the database with field layouts, in case I'm missing something obvious.

**Comment by darylknight** [comment]
Fun fact - this has just randomly stopped happening and everything is fine again. Weird! Thanks Josh - I'll ping you again if I can replicate. No idea why it wasn't / was working...

![image](https://user-images.githubusercontent.com/1250017/194813196-538cfa6f-274a-40e3-8045-1d173f86e307.png)

**Comment by tomkiss** [comment]
This is happening for me, i have 60 odd fields and all but 2 or 3 are saying unused.

This happened immediately after a Craft 4 upgrade. Have tried uninstalling and reinstalling, clearing caches - made no difference.

Very odd. Happy to send over a database dump if its helpful.

**Comment by engram-design** [comment]
That's pretty odd indeed! If you're able to shoot a database to `support@verbb.io` we can take a look at what's going on...

**Comment by engram-design** [comment]
Thanks for the export! It looks like this is due to your `craft_fieldlayoutfields` database table being out of date, compared to the serialized field layout element data that is in `craft_fieldlayouttabs`. That's why for entry types the fields are in there, but Field Manager will use the former database tables to look up against fields.

Re-saving your entry types and sections kick this into gear.
