### ISSUE TITLE
Changing between entry types doesn't update the fields

### ISSUE THREAD

**Issue by nateclonch** [engram-design/FieldManager#90]
### Describe the bug

This same issue was brought up here
https://github.com/craftcms/cms/issues/11537
but for me the issue disappeared after disabling the Field Manager plugin.

### Steps to reproduce

1. With the Field Manager plugin enabled, go to an entry with two entry types.
2. Toggle between the two types.

### Craft CMS version

4.2.4

### Plugin version

3.0.2

### Multi-site?

No

**Comment by engram-design** [comment]
I can't replicate this, sorry! Are there any JS error in your web developer tools console? Or any errors in your error logs at `/storage/logs`?

**Comment by nateclonch** [comment]
Well, I may have been wrong. After disabling and re-enabling the Field Manager plugin, there's no issue toggling between entry types. However, I'm confident that disabling/enabling the plugin played some part in the resolution of the issue.
