### ISSUE TITLE
Unable to clone Neo fields

### ISSUE THREAD

**Issue by tigerchick** [engram-design/FieldManager#91]
### Describe the bug

When I try to clone a NEO field it gives an error (and doesn't clone the field): 
Undefined array key "enabled"

### Steps to reproduce

1. Click "Clone" next to NEO field in Field Manager
2. Change field name to new field name in modal window.
3. Click "Clone" in modal window
4. Error is displayed in bottom left of window

### Craft CMS version

4.2.5.2

### Plugin version

3.0.2

### Multi-site?

No

### Additional context

NEO v3.4.0 installed

**Comment by engram-design** [comment]
Should be fixed in [3.0.3](https://github.com/verbb/field-manager/releases/tag/3.0.3)
