### ISSUE TITLE
Cloning Field with Link Field failed

### ISSUE THREAD

**Issue by samuelreichor** [engram-design/FieldManager#96]
### Describe the bug

Hi, I have isses cloning a craft matrix Field with a linkfield in it. I get that error:

lenz\linkfield\fields\LinkField::setTypeSettings(): Argument #1 ($value) must be of type array, stdClass given, called in /var/www/html/vendor/yiisoft/yii2/base/Component.php on line 180

### Steps to reproduce

1. Make a matrix field 
2. Add a link Field in that matrix field
3. Clone that matrix field

### Craft CMS version

4.4.14

### Plugin version

3.0.6

### Multi-site?

Yes

### Additional context

Typed link field version is 2.1.5

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/field-manager:"dev-craft-4 as 3.0.6"`.

**Comment by samuelreichor** [comment]
@engram-design Thanks a lot!!!!

**Comment by engram-design** [comment]
Fixed in [3.0.7](https://github.com/verbb/field-manager/releases/tag/3.0.7)
