### ISSUE TITLE
Field form validation errors are swallowed and data is being dismissed

### ISSUE THREAD

**Issue by buesing** [engram-design/FieldManager#97]
### Describe the bug

When creating an invalid new field (for example a matrix field with no block types) and trying to save, the dialog is being closed, no error is displayed and all the form data is thrown away. This has cost me some time when creating complex matrix fields, when one of the blocks has an invalid configuration the whole field is deleted upon save.

### Steps to reproduce

1. Go to field manager tab
2. Click "New Field"
3. Type some random name
4. Select Matrix type
5. Click save
6. Observe no field saved, no error shown

### Craft CMS version

Craft Pro 4.4.16

### Plugin version

3.0.7

### Multi-site?

No

### Additional context

All plugins:

Amazon S3 | 2.0.3
Field Manager 3.0.7
Neo 3.8.2
Redactor 3.0.4

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/field-manager:"dev-craft-4 as 3.0.7"`.

**Comment by engram-design** [comment]
Fixed in [3.0.8](https://github.com/verbb/field-manager/releases/tag/3.0.8)
